# Default variables, change these if you will
remote_user: ubuntu
ansible_ssh_user: ubuntu
sslcert: '/etc/ssl/forgeservicelab.fi.crt'
sslchain: '/etc/ssl/forgeservicelab.fi.crt.chain'
sslkey: '/etc/ssl/forgeservicelab.fi.key'
