# Default variables for testing targets, change these if you will
apache:
  allow_ip: "83.150.108.249" # Allow http connections from
  sslcert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'
  sslkey: '/etc/ssl/private/ssl-cert-snakeoil.key'
  # sslchain: '/etc/ssl/forgeservicela1b.fi.crt.chain'


